### ISSUE TITLE
Issue with Tokens.plist file when trying to build

### ISSUE THREAD

**Issue by iamdeadman** [StepicOrg/stepik-ios#453]
Hi, 

I am trying to build the project in Xcode 10.2 beta 3 and while building the project I am getting this error now - 

```
CopyPlistFile /Users/harshitladdha/Library/Developer/Xcode/DerivedData/Stepic-cznvupuxbopwcuensvmqgqfdukth/Build/Products/Debug-iphonesimulator/Stepic.app/Tokens.plist /Users/harshitladdha/urTutors/ios-samples/stepik-ios/Stepic/Tokens.plist (in target: Stepic)
    cd /Users/harshitladdha/urTutors/ios-samples/stepik-ios
    builtin-copyPlist --convert binary1 --outdir /Users/harshitladdha/Library/Developer/Xcode/DerivedData/Stepic-cznvupuxbopwcuensvmqgqfdukth/Build/Products/Debug-iphonesimulator/Stepic.app -- /Users/harshitladdha/urTutors/ios-samples/stepik-ios/Stepic/Tokens.plist
error: unable to read input file as a property list: The operation couldn’t be completed. (XCBUtil.PropertyListConversionError error 1.)
```

Can anyone help suggest a fix for this error or help me debug this deeper to figure out what the issue is with this Tokens.plist file

**Comment by anshulmittal712** [comment]
Seems like the Tokens.plist is ill-formatted. Xcode is unable to open the file, and throws a formatting error. It does not even present an option to view the file as source code, to make modifications.

Upon running plutil on Tokens.plist, I get the following:

> /Users/xyz/stepik-ios-master/Stepic/Tokens.plist: Unexpected character å at line 1

**Comment by iamdeadman** [comment]
I am guessing this has to something with the encryption added to the Tokens.plist file. 
So, if we cannot have access to the decrypted file @Ostrenkiy can you please help me find an alternate way to skip this file and try to build this project without the encrypted tokens.plist file

**Comment by lgruen** [comment]
Why did this get closed without any answer?

The readme states "We will be glad to see your pull requests!", but it's not clear at all how to build this with multiple git-crypt encrypted files.

I would have liked to send a detailed issue report for a reproducible crash when downloading courses, but can't get it to build.

If contributions are indeed encouraged, could you please add corresponding instructions to the readme file?
