### ISSUE TITLE
GoogleService-Info.plist is corrupt

### ISSUE THREAD

**Issue by mohsinka** [StepicOrg/stepik-ios#59]
Thanks for this awesome implementation of the App. However GoogleService-Info.plist is corrupt. Please fix and update. Its showing gibberish characters.. I understand it is SHA encoded but how do you suggest it would run with the project? @Ostrenkiy

**Comment by Ostrenkiy** [comment]
Hi!
In order to run the project you need to create your own GoogleService application and import your `GoogleService-info.plist` file. The original `GoogleService-info.plist` is encrypted for security reasons.
